import { ReactNode } from 'react'
import './globals.css'
import { Outfit } from 'next/font/google'
import Image from 'next/image'

import bg from '@/assets/bg.png'

const outfit = Outfit({ subsets: ['latin'], variable: '--font-outfit' })

export const metadata = {
  title: '404 Not Found',
  description: 'Generated by create next app',
}

const Background = () => {
  return (
    <Image
      alt="picture of a living room"
      src={bg}
      quality={100}
      fill
      sizes="100vh"
      style={{
        objectFit: 'cover',
        zIndex: '-20',
        backgroundPosition: 'center',
        backgroundRepeat: 'no-repeat',
      }}
      className="transition-all duration-300"
    />
  )
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={`${outfit.className} text-gray1`}>
        <Background />
        {children}
      </body>
    </html>
  )
}
